Vagrant.configure("2") do |config|
  config.vm.define :cliente do |cliente|
    cliente.vm.box = "bento/centos-7.9"
    cliente.vm.box = "miguel-rondon/vm_cliente"
    cliente.vm.box_version = "0.0.1"
    cliente.vm.network :private_network, ip: "192.168.50.4"
    cliente.vm.hostname = "cliente"
  end
  config.vm.define :servidor do |servidor|
    servidor.vm.box = "bento/centos-7.9"
    servidor.vm.box = "miguel-rondon/vm_server"
    servidor.vm.box_version = "0.0.3"
    servidor.vm.network :private_network, ip: "192.168.50.5", virtualbox__intnet: "lan_stev"
    servidor.vm.hostname = "servidor"
    servidor.vm.network "forwarded_port", guest: 80, host: 8080
  end
end
